server:
  port: 8086

eureka:
  client:
    service-url:
       #代表注册到eureka服务端的地址
       defaultZone: http://localhost:8084/eureka/
spring:
  application:
    name: service
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: gkh
    password: 111111
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: oracle.jdbc.pool.OracleDataSource
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gkh.springboot.model





