server:
  port: 8083

eureka:
  client:
    service-url:
       #代表注册到eureka服务端的地址
       defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: consumer

rocketmq1:
  name-server: 127.0.0.1:9876
  producer:
    isOnOff: on  #该应用是否启用生产者
    groupName: MyProducer #发送同一类消息的设置为同一个group，保证唯一
    namesrvAddr: 127.0.0.1:9876 #mq的nameserver地址
    maxMessageSize: 4096 #消息最大长度 默认1024*4(4M)
    sendMsgTimeout: 3000 #发送消息超时时间,默认3000
    retryTimesWhenSendFailed: 2 #发送消息失败重试次数，默认2
  consumer:
    isOnOff: on #该应用是否启用消费者
    groupName: MyConsumer #接收同一类消息的设置为同一个group，保证唯一
    namesrvAddr: 127.0.0.1:9876 #mq的nameserver地址
    topics: topic_one~* #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    consumeMessageBatchMaxSize: 1 #设置一次消费消息的条数，默认为1条
    consumeThreadMin: 20
    consumeThreadMax: 60

rocketmq:
  name-server: http://127.0.0.1:9876 #rocketmq服务地址
  producer:
    group: MyProducer2
    send-message-timeout: 3000 #消息发送超时时长

















