server:
  port: 8084

eureka:
  client:
    service-url:
       #代表注册到eureka服务端的地址
       defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: rocketmq

rocketmq:
  name-server: http://127.0.0.1:9876 #rocketmq服务地址
  producer:
    group: MyProducer2
    send-message-timeout: 3000 #消息发送超时时长
  consumer:
    group: MyConsumer2


















